### ISSUE TITLE
Provide function to clear data in the LocalDataProvider

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#117]
If I want to remove all rows and just show the header, I have to do that manually with `lineup.data.data.setData([])`. The setting itself works fine, but results in multiple errors later when rendering the body:

```
LineUpJS.js:3641
Uncaught (in promise) TypeError: Cannot read property '_rankings' of undefined
    at LocalDataProvider.rankAccessor (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:3641:20)
    at RankColumn.ValueColumn.getValue (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:986:21)
    at RankColumn.ValueColumn.getLabel (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:983:26)
    at SVGTextElement.<anonymous> (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:3848:43)
    at SVGTextElement.arguments.length.each.value.function.value.textContent (http://localhost:9000/bower_components/d3/d3.js:784:21)
    at http://localhost:9000/bower_components/d3/d3.js:962:16
    at d3_selection_each (http://localhost:9000/bower_components/d3/d3.js:968:30)
    at Array.d3_selectionPrototype.each (http://localhost:9000/bower_components/d3/d3.js:961:12)
    at Array.d3_selectionPrototype.text (http://localhost:9000/bower_components/d3/d3.js:783:36)
    at DerivedCellRenderer.DefaultCellRenderer.render (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:3848:12)


LineUpJS.js:3111
Uncaught (in promise) TypeError: Cannot read property '_index' of undefined
    at SelectionColumn.desc.accessor (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:3111:73)
    at SelectionColumn.ValueColumn.getValue (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:986:21)
    at SVGTextElement.<anonymous> (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:4152:43)
    at SVGTextElement.arguments.length.each.value.function.value.textContent (http://localhost:9000/bower_components/d3/d3.js:784:21)
    at http://localhost:9000/bower_components/d3/d3.js:962:16
    at d3_selection_each (http://localhost:9000/bower_components/d3/d3.js:968:30)
    at Array.d3_selectionPrototype.each (http://localhost:9000/bower_components/d3/d3.js:961:12)
    at Array.d3_selectionPrototype.text (http://localhost:9000/bower_components/d3/d3.js:783:36)
    at SelectionCellRenderer.render (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:4152:12)
    at Object.render (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:5204:30)


LineUpJS.js:3528
Uncaught (in promise) TypeError: Cannot read property 'symbol' of undefined
    at StringColumn.CommonDataProvider.rowGetter [as accessor] (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:3528:63)
    at StringColumn.ValueColumn.getValue (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:986:21)
    at StringColumn.getValue (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:1396:43)
    at StringColumn.ValueColumn.getLabel (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:983:26)
    at SVGTextElement.<anonymous> (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:3848:43)
    at SVGTextElement.arguments.length.each.value.function.value.textContent (http://localhost:9000/bower_components/d3/d3.js:784:21)
    at http://localhost:9000/bower_components/d3/d3.js:962:16
    at d3_selection_each (http://localhost:9000/bower_components/d3/d3.js:968:30)
    at Array.d3_selectionPrototype.each (http://localhost:9000/bower_components/d3/d3.js:961:12)
    at Array.d3_selectionPrototype.text (http://localhost:9000/bower_components/d3/d3.js:783:36)


LineUpJS.js:3528
Uncaught (in promise) TypeError: Cannot read property 'score' of undefined
    at NumberColumn.CommonDataProvider.rowGetter [as accessor] (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:3528:63)
    at NumberColumn.ValueColumn.getValue (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:986:21)
    at NumberColumn.getRawValue (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:1283:43)
    at NumberColumn.getValue (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:1290:22)
    at SVGRectElement.width (http://localhost:9000/bower_components/lineupjs/dist/LineUpJS.js:3936:46)
    at SVGRectElement.attrFunction (http://localhost:9000/bower_components/d3/d3.js:671:21)
    at http://localhost:9000/bower_components/d3/d3.js:962:16
    at d3_selection_each (http://localhost:9000/bower_components/d3/d3.js:968:30)
    at Array.d3_selectionPrototype.each (http://localhost:9000/bower_components/d3/d3.js:961:12)
    at Array.d3_selectionPrototype.attr (http://localhost:9000/bower_components/d3/d3.js:651:32)
```

![lineup_error](https://cloud.githubusercontent.com/assets/5851088/17254041/70653ebe-55b3-11e6-93ea-aec539c9644e.PNG)

To prevent this, the LocalDataProvider should provide a "correct" `clearData` function and/or the renderer should handle also empty datasets without errors.

**Comment by thinkh** [comment]
@sgratzl Please have a look into it later.

**Comment by sgratzl** [comment]
it is difficult to create a more direct way to set/reset the data, since it depends on the data provider. However, the errors should be gone.

**Comment by sgratzl** [comment]
@thinkh can you close this issue, if it works for your, please
